export const API_BASE = "https://norma.nomoreparties.space/api";

export const RESET_FORM_FAILED: "RESET_FORM_FAILED" = "RESET_FORM_FAILED";
export const RESET_FORM_SUCCESS: "RESET_FORM_SUCCESS" = "RESET_FORM_SUCCESS";
export const UPDATE_FORM_FAILED: "UPDATE_FORM_FAILED" = "UPDATE_FORM_FAILED";
export const UPDATE_FORM_SUCCESS: "UPDATE_FORM_SUCCESS" = "UPDATE_FORM_SUCCESS";
export const REGISTER_FORM_SUCCESS: "REGISTER_FORM_SUCCESS" =
  "REGISTER_FORM_SUCCESS";
export const REGISTER_FORM_FAILED: "REGISTER_FORM_FAILED" =
  "REGISTER_FORM_FAILED";
export const LOGIN_FORM_SUCCESS: "LOGIN_FORM_SUCCESS" = "LOGIN_FORM_SUCCESS";
export const LOGIN_FORM_FAILED: "LOGIN_FORM_FAILED" = "LOGIN_FORM_FAILED";
export const LOGOUT_FORM_SUCCESS: "LOGOUT_FORM_SUCCESS" = "LOGOUT_FORM_SUCCESS";
export const LOGOUT_FORM_FAILED: "LOGOUT_FORM_FAILED" = "LOGOUT_FORM_FAILED";
export const SET_USER_SUCCESS: "SET_USER_SUCCESS" = "SET_USER_SUCCESS";
export const SET_USER_FAILED: "SET_USER_FAILED" = "SET_USER_FAILED";
export const AUTH_CHECK: "AUTH_CHECK" = "AUTH_CHECK";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT: "REMOVE_INGREDIENT" = "REMOVE_INGREDIENT";
export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
  "GET_INGREDIENTS_FAILED";
export const SET_ACTIVE_INGREDIENT: "SET_ACTIVE_INGREDIENT" =
  "SET_ACTIVE_INGREDIENT";
export const SET_CURRENT_TAB: "SET_CURRENT_TAB" = "SET_CURRENT_TAB";
export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const INCREASE_INGREDIENT: "INCREASE_INGREDIENT" = "INCREASE_INGREDIENT";
export const DRAG_CONSTRUCTOR_INGREDIENTS: "DRAG_CONSTRUCTOR_INGREDIENTS" =
  "DRAG_CONSTRUCTOR_INGREDIENTS";
export const DRAG_BUN_INGREDIENT: "DRAG_BUN_INGREDIENT" = "DRAG_BUN_INGREDIENT";
export const SORT_INGREDIENTS_ON_DRAG: "SORT_INGREDIENTS_ON_DRAG" =
  "SORT_INGREDIENTS_ON_DRAG";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";

export const CLOSE_MODAL: "CLOSE_MODAL" = "CLOSE_MODAL";
export const OPEN_INGREDIENTS_MODAL: "OPEN_INGREDIENTS_MODAL" =
  "OPEN_INGREDIENTS_MODAL";
export const OPEN_ORDER_MODAL: "OPEN_ORDER_MODAL" = "OPEN_ORDER_MODAL";

export const POST_ORDER_INFO_SUCCESS: "POST_ORDER_INFO_SUCCESS" =
  "POST_ORDER_INFO_SUCCESS";
export const POST_ORDER_INFO_FAILED: "POST_ORDER_INFO_FAILED" =
  "POST_ORDER_INFO_FAILED";
